### ISSUE TITLE
[Bug]: Skill doesn't communicate with my HA instance

### ISSUE THREAD

**Issue by timothe** [keatontaylor/alexa-actions#207]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### What happened?

I followed the guide but hit a snag on [this step](https://github.com/keatontaylor/alexa-actions/wiki/Alexa-Talking-to-Home-Assistant-(The-Skill)).
The last check doesn't work. 
The checks before were successful: 
- Alexa media player module and custom data is set up in HA
- skill imported in AWS
- invocation name changed
- skill built
- code checked with URL and long life token and deployed
- HA configuration checked and reloaded
- HA accessible from https with custom url (implemented for a while)
- went through the prerequisites and all steps again

I used the fr_FR language with a french invocation word "sois cool".
The test tab is showing no json output and the bot is replying with "Un problème est survenu avec la réponse de la Skill demandée" (a problem occured with the skill response).
I don't see any call from the logs in HA.

What am I missing?

### Version

latest

### What Alexa device are you using?

Echo

**Comment by DEADSEC-SECURITY** [comment]
Are you sure you deployed and configured the skill using the alexa app?

**Comment by timothe** [comment]
I can see the "Alexa Actionable Notifications" enabled in the dev category in my Alexa app.
Is that what you meant?

**Comment by DEADSEC-SECURITY** [comment]
But in the mobile app did you install or setup the skill lik you do with other skills?

**Comment by DEADSEC-SECURITY** [comment]
In the mobile app, when you go to "YOUR SKILLS" under Dev do you see you custom skill there? And if you see it and click on it is it enabled?

Also are you using tokens or using the login with HA?

**Comment by DEADSEC-SECURITY** [comment]
can you activate debug mode try again and send me the logs?

**Comment by timothe** [comment]
I understand I need to set debug to true in the code, but I have no idea where to find the logs and can't find it on the wiki either. Where should I be looking?

**Comment by DEADSEC-SECURITY** [comment]
There should be a button called cloudwatch or logs in the top bar of the code editor

**Comment by timothe** [comment]
Gotcha! I see that it tried and failed accessing the URL of my HA instance, which is weird because that's the only URL I'm using from any endpoint - there's no IP whitelist or firewall rule to prevent that.
Plus, the certificate is valid.
But for good measure, I set the valid certificate to False in the code.
I tried again, same issue. See logs: 
[log-events-viewer-result.csv](https://github.com/keatontaylor/alexa-actions/files/12662078/log-events-viewer-result.csv)

**Comment by DEADSEC-SECURITY** [comment]
Your getting a TLS error, is your certificate from a certified authority? Are you using a domain or an IP?

**Comment by timothe** [comment]
I used another Alexa integration before without issue.
I'm using the Companion app an other things using this domain.
My web browser is connecting using this URL and saying the certificate is valid.
This is a fresh Let's Encrypt certificate, I'm using a wild card one which works flawlessly for months on this server. I really don't think this is the issue here.
I'm seriously out of ideas.
Do you know anything else that could explain the issue?

**Comment by DEADSEC-SECURITY** [comment]
Could be an outdated version of requests too. What library versions are you using and what python version?

**Comment by timothe** [comment]
According to the docs, Python version 3.7 and I just installed the library 0.10.1 today (although the [lambda function](https://github.com/keatontaylor/alexa-actions/blob/master/lambda/lambda_function.py) still shows 0.9.1).

**Comment by DEADSEC-SECURITY** [comment]
Yhe thats just, that I sometimes forget to update the version in the comment. Anyway what I meat was the requirments.txt file what do you have inside there?

**Comment by DEADSEC-SECURITY** [comment]
Also is your domain using TLS 1.0? Cuz thats considered insecure for todays standards so requests sometimes complaints about it and given that in the logs it specifies the TLS 1.0 issue it could be that.

**Comment by timothe** [comment]
![Screenshot 2023-09-20 at 09 10 42](https://github.com/keatontaylor/alexa-actions/assets/6997555/9104cce0-8d7a-46b2-ac7e-fbf8ca9068ac)

No, it's not that.
Is there any reason why AWS would not be able to communicate with my server?
Knowing that all other services can do it without issue?

**Comment by timothe** [comment]
Requirements.txt is the latest with:
```
isodate==0.6.0
boto3==1.9.216
ask-sdk-core==1.11.0
pydantic==1.10.4
```

**Comment by DEADSEC-SECURITY** [comment]
Lets try to force requests version 2 see if it works.

Can you add on a new line to your requirement's file this? `requests==2.31.0` and try again. Also check if the logs change from the error that was happening before. You can also try `requests==1.2.3` if the first attempt fails and see what happens.

**Comment by DEADSEC-SECURITY** [comment]
This should force version 2 of requests which might solve it since I think lambda functions come with version 1 by default if forcing version 2 doesnt work try forcing the latest version 1.

**Comment by timothe** [comment]
I did, deployed, tested, same result. Log enclosed: 
[log-events-viewer-result.csv](https://github.com/keatontaylor/alexa-actions/files/12673034/log-events-viewer-result.csv)

![Screenshot 2023-09-20 at 13 36 34](https://github.com/keatontaylor/alexa-actions/assets/6997555/70062492-dbd3-44c8-ae1b-af1dac5fe50f)

Would it be different if I switched from token to auth?

**Comment by DEADSEC-SECURITY** [comment]
Lets try forcing urllib3 to version 2 and see how it goes.
You can do so by adding a new line to your requirements file with this: `urllib3==2.0.5`

This is related to this issue I found: https://stackoverflow.com/questions/47516722/urllib-request-ssl-connection-python-3

Apparently urllib3 doesn't support tls 1.3 on version 1 so version 2 might fix it?

**Comment by DEADSEC-SECURITY** [comment]
> I did, deployed, tested, same result. Log enclosed: [log-events-viewer-result.csv](https://github.com/keatontaylor/alexa-actions/files/12673034/log-events-viewer-result.csv)
> 
> ![Screenshot 2023-09-20 at 13 36 34](https://user-images.githubusercontent.com/6997555/269284300-70062492-dbd3-44c8-ae1b-af1dac5fe50f.png)
> 
> Would it be different if I switched from token to auth?

My bad, wrong library. Check my last message. You can remove the requests library and use urllib3

**Comment by timothe** [comment]
No worries, thanks!
I tried, but got an error from the deployment: `ERROR: Cannot install boto3 and urllib3==2.0.5 because these package versions have conflicting dependencies`

**Comment by DEADSEC-SECURITY** [comment]
ok let me fix that dependency issue very quick ill send you an updated version of requiremnts file

**Comment by DEADSEC-SECURITY** [comment]
Try this:
```
isodate==0.6.0
ask-sdk-core==1.11.0
pydantic==1.10.4
boto3~=1.28.51
urllib3~=2.0.0
```

This should force urllib version 2+ and boto3 1.28+ which should now solve the conflict. I haven't tested these version upgrades so lets hope they don't break other stuff.

**Comment by DEADSEC-SECURITY** [comment]
If that doesn't work before reverting the requirements file, try changing the `class Borg` to the following:
```
class Borg:
    """Borg MonoState Class for State Persistence."""

    _shared_state = {}

    def __init__(self):
        self.__dict__ = self._shared_state


def _init_http_pool():
    return urllib3.PoolManager(
        cert_reqs="CERT_REQUIRED" if VERIFY_SSL else "CERT_NONE", timeout=urllib3.Timeout(connect=10.0, read=10.0),
        ssl_version=ssl.PROTOCOL_TLSv1_3
    )
```

This will force the requests to use TLS v1.3 which is what your using if 'm not mistaken

And in the top next to the other imports add the following: `import ssl`

**Comment by DEADSEC-SECURITY** [comment]
> If that doesn't work before reverting the requirements file, try changing the `class Borg` to the following:
> 
> ```
> class Borg:
>     """Borg MonoState Class for State Persistence."""
> 
>     _shared_state = {}
> 
>     def __init__(self):
>         self.__dict__ = self._shared_state
> 
> 
> def _init_http_pool():
>     return urllib3.PoolManager(
>         cert_reqs="CERT_REQUIRED" if VERIFY_SSL else "CERT_NONE", timeout=urllib3.Timeout(connect=10.0, read=10.0),
>         ssl_version=urllib3.util.ssl.PROTOCOL_TLS
>     )
> ```
> 
> This will force the requests to use TLS v1.3

Now it should be good for you to try. Sorry I did some changes @timothe

**Comment by DEADSEC-SECURITY** [comment]
Might need to force botocore version too. To be honest I would just allow TLS v1.0, v1.1, v1.2 and see if it works. Also revert your changes for now.

**Comment by timothe** [comment]
I reverted my changes.
I checked my security settings, and I was using the most strict security (TLS 1.3 only). I changed to accept 1.3/1.2/1.1/1.0 and did another test, same result. Logs here: 
[log-events-viewer-result.csv](https://github.com/keatontaylor/alexa-actions/files/12682391/log-events-viewer-result.csv)

**Comment by DEADSEC-SECURITY** [comment]
Weird, can you try again, has been 3 hours maybe it was cashing or something like that?

**Comment by DEADSEC-SECURITY** [comment]
Does your home assistant have https in the url in the code?
Can you send me a screenshot of the config to my email (amng835@gmail.com) so I can make sure thats not the issue?

**Comment by timothe** [comment]
No problem, I contacted you @DEADSEC-SECURITY.
I tried again after 2 hours and still the same issue on maximum compatibility mode.

**Comment by DEADSEC-SECURITY** [comment]
I have a possible solution @timothe for you to try.

Add this somewhere next to the import statements:
`from urllib3.exceptions import InsecureRequestWarning`

then after thee imports add this:
`urllib3.disable_warnings(category=InsecureRequestWarning)`

And see if it works.

**Comment by timothe** [comment]
![Screenshot 2023-09-21 at 17 56 47](https://github.com/keatontaylor/alexa-actions/assets/6997555/5fd30068-20b9-4f1b-b743-ca65a35ed8dc)

Same issue 😕 

[log-events-viewer-result.csv](https://github.com/keatontaylor/alexa-actions/files/12689204/log-events-viewer-result.csv)

**Comment by DEADSEC-SECURITY** [comment]
Can you try the code from this branch?
https://github.com/keatontaylor/alexa-actions/tree/207-bug-skill-doesnt-communicate-with-my-ha-instance

It basicaly now uses requests instead of urllib3 and lets see if that changes anything.

**Comment by timothe** [comment]
Imported, deployed, errored :( 
[log-events-viewer-result.csv](https://github.com/keatontaylor/alexa-actions/files/12699174/log-events-viewer-result.csv)

**Comment by DEADSEC-SECURITY** [comment]
I'm making a new skill on side with your domain to see if I can catch the error, because whats weird is that I tried doing the request in my computer to your domain and it worked.

Do you have any sort of anti-bot or firewall protecting your domain?

**Comment by DEADSEC-SECURITY** [comment]
@timothe to do the tests I need a TOKEN. Would you mind sending me a token via email? If you are ok with it make it admin permissions if not (I totally understand) make it be able to read entities at least so I can go past the initial "open actionable notifications" test.

**Comment by timothe** [comment]
I'm sorry, I can't do that.

**Comment by DEADSEC-SECURITY** [comment]
Ok I understand. I need to think of another way to test it out then.

**Comment by DEADSEC-SECURITY** [comment]
Have you tried recreating the skill?

**Comment by timothe** [comment]
I just did - with the same result. It's using the master branch though, if I'm correct.

**Comment by DEADSEC-SECURITY** [comment]
can you use the branch [207-bug-skill-doesnt-communicate-with-my-ha-instance](https://github.com/keatontaylor/alexa-actions/tree/207-bug-skill-doesnt-communicate-with-my-ha-instance) and test it?

**Comment by timothe** [comment]
I don't think it's possible to import from a specific branch, at least I haven't found a way. I could however recreate and change the files to the ones from the branch though.
I just did that, and I get the same error.

**Comment by DEADSEC-SECURITY** [comment]
Sorry didn't read the hole answer, did you deploy the code changes? Same error in logs?

**Comment by timothe** [comment]
That's what I did.

**Comment by DEADSEC-SECURITY** [comment]
Dont revert to master yet. Continue using that branch. Ill try another thing and update the branch and let you know so you can test

**Comment by DEADSEC-SECURITY** [comment]
Could be this causing the issue: https://github.com/python/cpython/issues/80665#issuecomment-1676743165

Can you reactivate TLS 1.2 please?

**Comment by DEADSEC-SECURITY** [comment]
And disable TLS 1.3. Let me know when its done so i can check if its working and we can re test. Maybe giving the option for TLS 1.3 is making python select it and then run into issues. Not having tls 1.3, if it works we know whats the issue and its easier to solve.

**Comment by DEADSEC-SECURITY** [comment]
This is my HA domain config:
![image](https://github.com/keatontaylor/alexa-actions/assets/45077772/4a75f134-34b7-4a6c-9957-274afc95cd6a)

And this is yours:
![image](https://github.com/keatontaylor/alexa-actions/assets/45077772/a878aae4-dd44-4b66-90ff-e5d35840456d)

Your domain is too strict. Let me know when you activated TLS  1.2 and removed TLS 1.3 so i can re check and we can test

**Comment by timothe** [comment]
I switched the subdomain just now for compatibility with TLS 1.2.
But I scanned it with SSL Labs and it's indicating it's still stuck with 1.3 for now 🤔

**Comment by DEADSEC-SECURITY** [comment]
Checking rn again.

**Comment by DEADSEC-SECURITY** [comment]
Still 1.3 only. Did you change anything? Also what are you using from Synology to serve HA?

**Comment by timothe** [comment]
I don't achieve to do that... checking it again, it sticks with TLS 1.3.
My flow is: DN provider -> my NAS IP -> DSM reverse proxy + Let's Encrypt certificate
The subdomain for HA is supposedly set to "Intermediate compatibility" which is accepting TLS 1.2.
![image](https://github.com/keatontaylor/alexa-actions/assets/6997555/934894cd-e481-4d96-96aa-9e3ff58173c5)

Is there a way to use a modern encryption standard, TLS 1.3?

**Comment by DEADSEC-SECURITY** [comment]
@timothe so far not its not possible since lambda doesn't seem to support such CIPHERS and TLS. In my local machine it works but within the lambda doesn't seem to be working which means that the lambda doesn't have the supported CIPHERS and drivers for TLS 1.3.
This is my theory of course.

Another thing, do you have HSTS active? Can you try disabling it? And trying again. Dont revert right away, let me do a scan first.

You could try cloudflare tunnels to see if that works. I use them and its very good and they support all TLS and CIPHER protocols and its easier to do mods.

**Comment by DEADSEC-SECURITY** [comment]
There is a way actually, but you have to host the skill locally in your machine and make it available to Alexa skills. If you do so you can control everything in the env and fix the issue.

This skill doesn't support self hosting so you need to make modifications to the code before.

**Comment by DEADSEC-SECURITY** [comment]
There is another way that I just remembered but I haven't tested. You can create a AWS account and host the code in a lambda function in AWS. AWS allows you to choose python 3.9, 3.10 and 3.11 which should come with the latest versions of boto3 and urllib and possibly allow for TLS 1.3 support. Its also easier to add stuff to a lambda at AWS since you can create layers with required libs, binaries etc.

**Comment by timothe** [comment]
> Another thing, do you have HSTS active? Can you try disabling it? And trying again. Dont revert right away, let me do a scan first.

I deactivated it for this subdomain just now. Feel free to do a test. To me, that's the last resort before I drop this project.

**Comment by DEADSEC-SECURITY** [comment]
Still stuck in 1.3. Did you test on your side too?

**Comment by timothe** [comment]
Yep, still stuck indeed. But I tried something: move my entire server in compatibility mode to accept TLS 1.2 and 1.3.
Then the server replied:
```
{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "SSML",
				"ssml": "<speak>Désolé je n'ai pas compris... <break time='200ms'/> Désolé, j'ai quelques problèmes, veuillez verifier votre configuration dans votre skill personnalisé et essayez à nouveau..</speak>"
			},
			"reprompt": {
				"outputSpeech": {
					"type": "SSML",
					"ssml": "<speak></speak>"
				}
			},
			"shouldEndSession": false,
			"type": "_DEFAULT_RESPONSE"
		},
		"sessionAttributes": {},
		"userAgent": "ask-python/1.11.0 Python/3.7.17"
	}
}
```
We're getting somewhere! See the log: 
[log-events-viewer-result.csv](https://github.com/keatontaylor/alexa-actions/files/12715963/log-events-viewer-result.csv)
I think that's expected... right?

So I was looking at [this step](https://github.com/keatontaylor/alexa-actions/wiki/Home-Assistant-Talking-to-Alexa-(The-Script)), and I'm not sure what my Skill ID is?

**Comment by DEADSEC-SECURITY** [comment]
Yes, just checked with sslabs and TLS 1.2 is now active.

![Screenshot_20230925_102131_Brave.jpg](https://github.com/keatontaylor/alexa-actions/assets/45077772/720765aa-43e7-49dc-b1ff-b501f8efc514)

And from your logs yes seems to be working. Can you try triggering the skill from HA now?

**Comment by DEADSEC-SECURITY** [comment]
In the tutorial it should tell you how to find thr skill ID. You can also search online. Im not in my pc right now and I don't know the exact steps by heart but let me know if you still can't find it.

**Comment by timothe** [comment]
Ok I found it, no worries. But we're not out of the woods yet. The [test](https://github.com/keatontaylor/alexa-actions/wiki/Home-Assistant-Talking-to-Alexa-(The-Script)#checking-success) doesn't work.

- Is the skill listed within your Alexa App on your Smartphone? YES
- Is the volume up? YES
- Did you connect your device and not to a device of your wife's or husband's account? YES
- Did you provide the right ID of your skill? YES
- In the developer console check the Analytics of your skill. (Utterances count up with some latency.) Erm, not sure? I see a number of requests from the "usage" page

No event is fired when I listen to it from the developer tools. No response when calling the service. Nothing in logs.

**Comment by DEADSEC-SECURITY** [comment]
How are you calling the skill?

**Comment by DEADSEC-SECURITY** [comment]
When you triggered the skill did alexa say anything? Did you select the correct alexa device ID?

**Comment by timothe** [comment]
FYI I updated HA Core and Alexa Media Player with the latest today, same issue.

**Comment by ziggycatuk** [comment]
bumping this in the hope the owner will investigate as this seems to be a common issue.  

with all pre requirements fulfilled and following the install instruction to the letter:
The dev console communicates with HA and successfully reads back the data from the text helper - all good.
However trying to initiate the script from dev > services does nothing, no response from Alexa and no errors produced.

any help appreciated

**Comment by DEADSEC-SECURITY** [comment]
Can you share the service call your using to call the skill @timothe @ziggycatuk

**Comment by ziggycatuk** [comment]
```
service: script.activate_alexa_actionable_notification
data:
  text: "Yes or no?"
  event_id: "alexa_actionable_notification_test"
  alexa_device: media_player.living_room
```

**Comment by timothe** [comment]
More or less the same:
```
service: script.activate_alexa_actionable_notification
data:
  text: Allo le monde ?
  event_id: alexa_actionable_notification_test
  alexa_device: media_player.studio
```

**Comment by DEADSEC-SECURITY** [comment]
Have you guys tried not using the script and running the service yourselves?

**Comment by timothe** [comment]
1. Not sure how to do that
2. It's not documented
3. Why would I need to do that if the dev tools is doing exactly the same?

**Comment by ziggycatuk** [comment]
I think he means calling the service directly, I've already tried this and it still doesn't work.

```
service: media_player.play_media
data:
  entity_id: media_player.living_room
  media_content_type: skill
  media_content_id: amzn1.ask.skill.48140020-d386-4e19-9463-c73675a25007

```

**Comment by DEADSEC-SECURITY** [comment]
> 1. Not sure how to do that
> 2. It's not documented
> 3. Why would I need to do that if the dev tools is doing exactly the same?

What @ziggycatuk did @timothe.
We are debugging, so we need to exclude all possibilities. We never know, the script could be bugged and could've been the reason.

**Comment by DEADSEC-SECURITY** [comment]
> I think he means calling the service directly, I've already tried this and it still doesn't work.
> 
> ```
> service: media_player.play_media
> data:
>   entity_id: media_player.living_room
>   media_content_type: skill
>   media_content_id: amzn1.ask.skill.48140020-d386-4e19-9463-c73675a25007
> ```

but you can make the alexa device speak using the services right?

**Comment by ziggycatuk** [comment]
> > I think he means calling the service directly, I've already tried this and it still doesn't work.
> > ```
> > service: media_player.play_media
> > data:
> >   entity_id: media_player.living_room
> >   media_content_type: skill
> >   media_content_id: amzn1.ask.skill.48140020-d386-4e19-9463-c73675a25007
> > ```
> 
> but you can make the alexa device speak using the services right?

Yes, using calling the alexa.notify service has always worked.

**Comment by DEADSEC-SECURITY** [comment]
What local is your alexa skill? What language did you select for the skill?

**Comment by DEADSEC-SECURITY** [comment]
@timothe are you using cloudflare proxy by any chance? Or are you just using synology? Have you tried using cloudflare tunnels to see if it fixes this issue? Maybe also see if there are no firewall rules in your synology that could be impacting this? Temporarly disabling your firewall and testing could help understand if there is a problem there.

**Comment by timothe** [comment]
@DEADSEC-SECURITY I'm on FR-FR for the skill, the account is probably GB-EN, and my Echo devices are FR-CA.
I'm not using Cloudflare, but I have in the past and I had various issues, depending on the service. I may use it for HA but in general. The firewall is quite loose on the services I defined, with the condition to use TLS 1.2 or 1.3.
Other services are interacting with the server without any issue.

**Comment by timothe** [comment]
Ok there's news!
I changed the Echo devices locale to fr_FR and I got a notification on my device in French in the likes of "Sorry, I didn't understand. I have some issues, check..." and then is waiting for further voice input, and stops.
On the listening side, I still get nothing.
![Screenshot 2023-10-24 at 13 44 45](https://github.com/keatontaylor/alexa-actions/assets/6997555/43b6e801-97fb-4af9-bfab-3fd6541b2658)

**Comment by DEADSEC-SECURITY** [comment]
Logs ... @timothe

**Comment by timothe** [comment]
Sorry, here it is. 
[log-events-viewer-result.csv](https://github.com/keatontaylor/alexa-actions/files/13117170/log-events-viewer-result.csv)

**Comment by DEADSEC-SECURITY** [comment]
Thats actually very good @timothe. The erros is complaining that event_id was not defined, can you double check the data your sending to the alexa skill?

**Comment by timothe** [comment]
I'm following the [guide](https://github.com/keatontaylor/alexa-actions/wiki/Home-Assistant-Talking-to-Alexa-(The-Script)#checking-success). The script has been defined as described in the guide as well.

![Screenshot 2023-10-24 at 23 20 15](https://github.com/keatontaylor/alexa-actions/assets/6997555/a252037a-bcf9-4555-9b58-957b0bfb9482)
![Screenshot 2023-10-24 at 23 20 08](https://github.com/keatontaylor/alexa-actions/assets/6997555/afa0979e-e064-4d20-a3eb-661c55a024cd)

Can you confirm the data is right?

**Comment by DEADSEC-SECURITY** [comment]
Can you put quotes around the text and event_id? Also add suppress_confirmation to the data. Set it as false

**Comment by timothe** [comment]
I did, exact same result and behaviour.
```
service: script.activate_alexa_actionable_notification
data:
  text: "Bonjour !"
  event_id: "alexa_actionable_notification_test"
  alexa_device: media_player.studio
  suppress_confirmation: false
```

**Comment by DEADSEC-SECURITY** [comment]
Are you getting any errors in the logs?

**Comment by timothe** [comment]
Same output as before `AttributeError: 'HaStateError' object has no attribute 'event_id'` etc

**Comment by DEADSEC-SECURITY** [comment]
What version of the code are you using? Any other error messages or clues from the satck trace?

**Comment by timothe** [comment]
I didn't change the code since the last time, still on v0.9.1. Not sure what you're referring to for the stack trace?

**Comment by DEADSEC-SECURITY** [comment]
can you update the code to v0.10.1 or master branch?

**Comment by timothe** [comment]
It... works.
I re-created the skill from scratch, imported the repo, and I now get a proper response and trigger in HA.
For extra brownie points I tried with TLS 1.2 and 1.3, and I can confirm it only works on TLS 1.2 ⚠️
Thank you so much for your patience.

Extra question: do you know or plan to link the HA voice assistant to this Alexa skill?

**Comment by ziggycatuk** [comment]
hey @timothe - do you mind sharing exactly how you done this.

which repo did you import,  what language, account linking or HA Token ?

**Comment by DEADSEC-SECURITY** [comment]
> It... works.
> I re-created the skill from scratch, imported the repo, and I now get a proper response and trigger in HA.
> For extra brownie points I tried with TLS 1.2 and 1.3, and I can confirm it only works on TLS 1.2 ⚠️
> Thank you so much for your patience.
> 
> Extra question: do you know or plan to link the HA voice assistant to this Alexa skill?

I had an idea of doing so, but as as paid service since it requires running servers to make it easier to setup. I have a discussion open regarding that in discussions if you would like to share your thoughts.

**Comment by timothe** [comment]
@ziggycatuk I followed the guide again, I used a consistent locale (fr_FR) between my skill and my Echo devices, and I downgraded my security to accept TLS 1.2.
@DEADSEC-SECURITY yes I'd be interested, and this could be a core project to gain more adoption for the assistant, but I don't think it would require a 3rd party server?

**Comment by ziggycatuk** [comment]
@timothe - Be really grateful if you could provide a little more info.  This really has me going round in circles.

* Could you share the repo link you used.
* Are you using account linking or a homeassistant token when creating the skill ?
* how did you set your security to use TLS 1.2 ?

Many thanks

**Comment by DEADSEC-SECURITY** [comment]
> @ziggycatuk I followed the guide again, I used a consistent locale (fr_FR) between my skill and my Echo devices, and I downgraded my security to accept TLS 1.2. @DEADSEC-SECURITY yes I'd be interested, and this could be a core project to gain more adoption for the assistant, but I don't think it would require a 3rd party server?

https://github.com/keatontaylor/alexa-actions/discussions/209

**Comment by timothe** [comment]
> #209

That's not what I meant. I'm thinking connecting [HA Voice Control](https://www.home-assistant.io/voice_control/) to Alexa. The workflow would be:
User > Alexa command > HA VC query + reply > Alexa output
Any plan for that?

> @timothe - Be really grateful if you could provide a little more info. This really has me going round in circles.
> 
> * Could you share the repo link you used.
This very same repo, url from the guide
> * Are you using account linking or a homeassistant token when creating the skill ?
Token, as described above
> * how did you set your security to use TLS 1.2 ?
In DSM7, switch the Security setting in the Control Panel to Intermediate compatibility.
